### PR TITLE
Geocode

### PR DESCRIPTION
**Pull request by tanguilb**
Hi,
I finish to geocode address and show on map the different result of the query.

### CODE REVIEW

**Comment by rand74** [comment]
Hello, good job it's ok for me

**Comment by Gianni-n** [comment]
it seems good for me too

**Comment by Axelle-slv** [comment]
Hello Tangui,
I just have two things to back up to you : why did you call your file "googlemap.js" on base.html.twig ? It will be called and download on every page of the website, even if we don't need it and will slow down its performances (idem for David for its files autocomplete.js and searchcity.js). You have to call it in the {% block javascript %} of the page you need it. Moreover, there is about fifteen empty lines at the end of this file.

**Comment by tanguilb** [comment]
Hello Axelle.
i call file googlemap.js on base because i think we need on two page the search page and the organization page. the map appears on this two page with the geolocalisation. Perhaps it will be better to call it only on this two page?

**Comment by Axelle-slv** [comment]
Hello Tangui,
Yes I think it would be better to call this file only on your two pages, because if you call it on base.html-twig, it will be loaded on all pages that extend base.html.twig, even if the map not does appear on these pages. So it will lenth the time of loading of these pages.

**Pull request merged**
